set(CXX_FILES
	# Headers
	src/PCH.h
	src/Kudasai/Misc.h
	src/Kudasai/Defeat.h
	src/Kudasai/Animation/Animation.h
	src/Kudasai/Combat/Hooks.h
	src/Kudasai/Combat/Resolution.h
	src/Kudasai/Combat/Zone.h
	src/Kudasai/Interface/Interface.h
	src/Kudasai/Interface/QTE.h
	src/Kudasai/Struggle/Struggly.h
	src/Papyrus/Property.h
	src/Papyrus/Functions.h
	src/Papyrus/Settings.h
	src/Serialization/Storage.h
	src/Serialization/KeywordManager.h
	# C++
	src/main.cpp
	src/Kudasai/Misc.cpp
	src/Kudasai/Defeat.cpp
	src/Kudasai/Animation/Animation.cpp
	src/Kudasai/Combat/Hooks.cpp
	src/Kudasai/Combat/Resolution.cpp
	src/Kudasai/Combat/Zone.cpp
	src/Kudasai/Interface/QTE.cpp
	src/Kudasai/Struggle/Struggly.cpp
	src/Papyrus/Functions.cpp
	src/Papyrus/Settings.cpp
)
